services:
  - type: web
    name: frontend
    env: static
    staticPublishPath: build
    buildCommand: npm install && npm run build
    rootDir: client

  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    rootDir: server
